### ISSUE TITLE
Unable to install the app

### ISSUE THREAD

**Issue by sagorahmed** [ZoidbergZero/MusicMan#1]
#### Expected behavior
The users should be able to install the app without getting any trouble.

#### Actual behavior
The app displayed an error while I tried to install after downloading it successfully.

#### How to reproduce
1. Download the app.
2. When the app will download successfully. Try to install it and noticed the error.

* App version: v0.1
* Operating system: Android 6.0.1

**Comment by ZoidbergZero** [comment]
You probably have to allow Apps from Unknown Sources or Disable PlayProtect, as this App is not yet Signed.

If you provide me more Information about the Error Message i would be glad to Help you out.

**Comment by ZoidbergZero** [comment]
Fixed in 02309d84273a7f195daa60b595a8313442e7c79e
