### ISSUE TITLE
[ MusicMan] the  wrong version  mantion in letest release 

### ISSUE THREAD

**Issue by XAMIR555** [ZoidbergZero/MusicMan#3]
#### Project Information
* Repository    :  https://github.com/ZoidbergZero/MusicMan
* Project Name  : MusicMan
* Publisher     :  zoidbergZero

#### Expected behavior

I expected that  according to title should be avaliable  the letest version of application 0.2

#### Actual behavior

In the title mantion the lestes version of application 0.2 but when i install and see the application version is 0.1

#### How to reproduce
*  [open the link](https://github.com/ZoidbergZero/MusicMan/releases) 
* click on 0.2  amd download it
* intall the application
* see the version of application 
* 
* Note the Bug
* Browser/App version:  0.1
* Operating system:  8.0.0

#### GitHub Account
https://github.com/XAMIR555
#### Recording Of The Bug

https://youtu.be/Cr3IDuerq3s

**Comment by ZoidbergZero** [comment]
Version Indicator Coming in Version 0.3
