### ISSUE TITLE
A guide for contributors.

### ISSUE THREAD

**Issue by HarryHeights** [ZoidbergZero/MusicMan#5]
Hi, would you like a document that will help prospective collaborators contribute to your project?

**Comment by ZoidbergZero** [comment]
Hello, I planned this Project more as an Small One Man Side Project , but shure send over. :)

**Comment by HarryHeights** [comment]
I'll send a pull request soon

**Comment by ZoidbergZero** [comment]
Thanks alot :) Closing the Issue now.
